on:
  pull_request:
    branches:
      - master
      - development

  push:
    branches:
      - master
name: "Build and Released Book Ticket Flutter App"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the time
        id: time
        run:
          NOW=$(date +"%r")
          echo "now=${NOW}" >> $GITHUB_OUTPUT
        env:
          TZ: Europe/Rome
      - uses: actions/setup-java@v1
        with:
          java-version: '23.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.29.1'
      - run: flutter pub get
      - run: flutter --version
      - run: flutter build apk --debug --split-per-abi
      - name: push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          tag: v0.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
